# Generated by Django 3.0.5 on 2023-05-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumEp', models.CharField(max_length=1000)),
                ('enajenante', models.CharField(max_length=1000)),
                ('adquiriente', models.CharField(max_length=1000)),
                ('isai', models.CharField(max_length=1000)),
                ('isr', models.CharField(max_length=1000)),
            ],
        ),
    ]
