# Generated by Django 3.0.5 on 2023-05-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='adquiriente',
            new_name='Adquiriente',
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='enajenante',
            new_name='Enajenante',
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='isai',
            new_name='Isai',
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='isr',
            new_name='Isr',
        ),
    ]
