# Generated by Django 3.0.5 on 2023-05-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_auto_20230516_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
